export const CONSTANTS = {
    INIT_APP: 'INIT_APP',
    SPLASH_SCREEN_HIDE_REQUEST: 'SPLASH_SCREEN_HIDE_REQUEST',
    SPLASH_SCREEN_HIDE_SUCCESS: 'SPLASH_SCREEN_HIDE_SUCCESS',

    WELCOME_SCREEN_VIEW_REQUEST: 'WELCOME_SCREEN_VIEW_REQUEST',
    WELCOME_SCREEN_VIEW_SUCCESS: 'WELCOME_SCREEN_VIEW_SUCCESS',
}